name: Publish NuGet Package
on:
  push:
    branches:
      - 6-create-gh-action-to-publish-to-nugetcom
  #push:
  #  tags:
  #    - 'v*'

env:
  dotnetVersion: 7.0.x
  testProjectPath: test/Idam.Libs.EF.Tests
  srcProjectPath: src/Idam.Libs.EF

jobs:
  test:
    name: "Test the package before publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${dotnetVersion}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${dotnetVersion}

      - name: Restore dependencies 
        run: dotnet restore test/Idam.Libs.EF.Tests

      - name: Build library
        run: dotnet build test/Idam.Libs.EF.Tests --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  publish:
    name: "Build, Pack, and Publish package to NuGet.org"
    runs-on: ubuntu-latest
    
    needs: test
    if: ${{ needs.test.result == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK $dotnetVersion
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: $dotnetVersion

      - name: Restore dependencies
        run: dotnet restore src/Idam.Libs.EF

      - name: Build library
        run: dotnet build src/Idam.Libs.EF --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack src/Idam.Libs.EF --configuration Release --no-build --output ./output

      - name: Publish to NuGet.org
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
