name: Publish NuGet Package
on:
  push:
    branches:
      - 6-create-gh-action-to-publish-to-nugetcom
  #push:
  #  tags:
  #    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Change to the appropriate version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build library
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./output

      #- name: Publish to NuGet.org
      #  run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
