name: Test NuGet Package
on: [push]

env:
  dotnetVersion: 9.x.x
  testProjectPath: Idam.EFTimestamps.Tests
  srcProjectPath: Idam.EFTimestamps

jobs:
  test:
    name: "Test the package before publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ env.dotnetVersion }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnetVersion }}

      - name: Setup Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore dependencies 
        run: dotnet restore ${{ env.testProjectPath }}

      - name: Build library
        run: dotnet build ${{ env.testProjectPath }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.testProjectPath }} --no-restore --verbosity normal
