name: Test NuGet Package
on: [push]

env:
  dotnetVersion: 8.x.x
  testProjectPath: Idam.EFTimestamps.Tests
  srcProjectPath: Idam.EFTimestamps

jobs:
  test:
    name: "Test the package before publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ env.dotnetVersion }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnetVersion }}

      - name: Setup Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore Idam.EFTimestamps dependencies
        run: dotnet restore ${{ env.srcProjectPath }}

      - name: Build Idam.EFTimestamps library
        run: dotnet build ${{ env.srcProjectPath }} --configuration Release --no-restore

      - name: Test Idam.EFTimestamps
        run: dotnet test ${{ env.srcProjectPath }} --no-restore --verbosity normal

      - name: Restore Idam.EFTimestamps.Tests dependencies 
        run: dotnet restore ${{ env.testProjectPath }}

      - name: Build Idam.EFTimestamps.Tests library
        run: dotnet build ${{ env.testProjectPath }} --configuration Release --no-restore

      - name: Test Idam.EFTimestamps.Tests
        run: dotnet test ${{ env.testProjectPath }} --no-restore --verbosity normal
