name: Test NuGet Package
on: [push]

env:
  dotnetVersion: 7.0.x
  testProjectPath: test/Idam.Libs.EF.Tests

jobs:
  test:
    name: "Test the package before publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ env.dotnetVersion }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnetVersion }}

      - name: Setup Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore dependencies 
        run: dotnet restore ${{ env.testProjectPath }}

      - name: Build library
        run: dotnet build ${{ env.testProjectPath }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.testProjectPath }} --no-restore --verbosity normal
